#!/usr/bin/env bash
# displays numbers from 1 to 20 and:
# displays 4 and then 'bad luck from China' for the 4th loop iteration,
# 'bad luck from Japan' for the 9th loop iteration, and
# 'bad luck from Italy' for the 17th loop iteration

r=1
while [ $r -le 20 ]
do
	echo $r

	case $r in
		4)
		echo "bad luck from China" ;;
	9)
		echo "bad luck from Japan" ;;
	17)
		echo "bad luck from Italy" ;;
	esac

	((r+=1))
done
